### ISSUE TITLE
Poposdetails.js img src issue

### ISSUE THREAD

**Issue by yshwanth** [MakeSchool-Tutorials/React-Fundamentals#3]
img src not displaying in poposdetails

**Comment by ibirnam** [comment]
@yashwanthambati - just ran the finished tutorial, and I am able to see the img src on poposdetails. Make sure to check the following:

- Are your images located within the public folder? i.e. `public/images/` where `public` is at the same hierarchy as `src`?
- in `POPOSDetails.js`, your `img` tag looks like the following: 
```
<img src={`${process.env.PUBLIC_URL}images/${images[0]}`} />
```
- You are properly importing the JSON using `import data from './sfpopos-data.json'`
- `images` is included in the following definition: `const { images, title, desc, hours, features, geo } = data[id]`

Check all of those first, and that should fix it!
