### ISSUE TITLE
7. Organizing Files

### ISSUE THREAD

**Issue by chrismlee26** [MakeSchool-Tutorials/React-Fundamentals#4]
All of your components should now be in the components folder, except for index.js and index.css. After this change, your folder structure should look like the following:

src
components
About.js
App.css
App.js
App.test.js
POPOSDetails.js
POPOSList.css
POPOSList.js
POPOSSpace.css
POPOSSpace.js
Title.css
Title.js
index.css
index.js
serviceWorker.js
setupTests.js
sfpopos-data.json.  <---- Should remain inside src, not be moved into components. Later in the tutorial it is outside but on this step it is inside.

**Comment by ibirnam** [comment]
thanks for finding this @chrismlee87 ! Fix has been pushed!
