### ISSUE TITLE
URL's to download images and json files are not found

### ISSUE THREAD

**Issue by elzabeth** [MakeSchool-Tutorials/React-Fundamentals#6]
The "**SFPOPOS-images**" folder in section 3 and the "**sfpopos-data.json file**" folder in section 5 is not accessible.
Error-404 was found when tried to access this public folder.

**Comment by soggybag** [comment]
You should use the updated tutorial here: https://github.com/Tech-at-DU/React-Fundamentals-tutorial

We've moved the MakeSchool CS program to Dominican University. All of the curriculum has been moved there and will be updated from there. 

All of the courses and tutorials are in the tech at DU repo here: https://github.com/Tech-at-DU

**Comment by elzabeth** [comment]
ok sure, Thank you. Will use that.
